# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Event-driven microservices CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  artifact:
    name: Publish Artifacts
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Publish artifact in Github Packages
        run: mvn --batch-mode deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  test:
    name: Unit-test
    runs-on: [ ubuntu-latest ]
    needs: [ artifact ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for testing
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run maven tests
        run: mvn clean test --file pom.xml


  docker:
    name: Create Docker Images
    runs-on: [ ubuntu-latest ]
    timeout-minutes: 10
    needs: [ test, artifact ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for Docker Images
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build Java packages for docker
        run: mvn clean package --file pom.xml
      - name: Build and run docker containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Stop the containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down



